# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(327, 294)
        MainWindow.setMinimumSize(QtCore.QSize(327, 294))
        MainWindow.setMaximumSize(QtCore.QSize(327, 294))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Human_Label = QtWidgets.QLabel(self.centralwidget)
        self.Human_Label.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.Human_Label.setObjectName("Human_Label")
        self.Alien_Label = QtWidgets.QLabel(self.centralwidget)
        self.Alien_Label.setGeometry(QtCore.QRect(10, 50, 191, 16))
        self.Alien_Label.setObjectName("Alien_Label")
        self.Human_Entry = QtWidgets.QLineEdit(self.centralwidget)
        self.Human_Entry.setGeometry(QtCore.QRect(200, 20, 113, 20))
        self.Human_Entry.setObjectName("Human_Entry")
        self.Alien_Entry = QtWidgets.QLineEdit(self.centralwidget)
        self.Alien_Entry.setGeometry(QtCore.QRect(200, 50, 113, 20))
        self.Alien_Entry.setObjectName("Alien_Entry")
        self.ENT_Label = QtWidgets.QLabel(self.centralwidget)
        self.ENT_Label.setGeometry(QtCore.QRect(80, 0, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        self.ENT_Label.setFont(font)
        self.ENT_Label.setObjectName("ENT_Label")
        self.Instructions_Label = QtWidgets.QLabel(self.centralwidget)
        self.Instructions_Label.setGeometry(QtCore.QRect(10, 110, 301, 151))
        self.Instructions_Label.setText("Welcome to the ENT Office Q-tip budget calculator, Doctor!\n\nUnfortunately, this application has no function to translate \nalien numbers. Please submit Arabic numerals denoting how \nmany clients you have of each species and this calculator will \ndetermine how much money you will need to spend on Q-tips \nto clean their ears!\n\nNote: Individual Q-tips cost $0.01 each, however boxes of \n500 cost $4.00 each and boxes of 1000 cost $7.00 each.\nThis program will pick the best deal for you!")
        self.Instructions_Label.setObjectName("Instructions_Label")
        self.Submit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Submit_Button.setGeometry(QtCore.QRect(60, 70, 75, 23))
        self.Submit_Button.setObjectName("Submit_Button")
        self.Clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_Button.setGeometry(QtCore.QRect(170, 70, 75, 23))
        self.Clear_Button.setObjectName("Clear_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 327, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Human_Label.setText(_translate("MainWindow", "How many human clients do you have?"))
        self.Alien_Label.setText(_translate("MainWindow", "How many alien clients do you have?"))
        self.ENT_Label.setText(_translate("MainWindow", "ENT Office Q-tip budget calculator"))
        self.Submit_Button.setText(_translate("MainWindow", "Submit"))
        self.Clear_Button.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
